### PR TITLE
fix: properly parse userinfo in uri

### PR DESCRIPTION
**Pull request by zekth**
Try addressing #100

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by zekth** [comment]
@Uzlopak could you please take a look? 🙏

**Review by gurgunday — APPROVED** [review]
yes lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by zekth** [comment]
@gurgunday @mcollina could you make a release?

**Pull request merged**
