### PR TITLE
use `tape`

### PR DESCRIPTION
**Pull request by gurgunday**
I replace-all'd a lot of things so let me know if I missed anything important

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
LGTM

**Review by zekth — APPROVED** [review]
excellent

**Review by mcollina — COMMENTED** [review]
Can you add back Node.js v16?

**Comment by gurgunday** [comment]
https://github.com/fastify/fast-uri/blob/main/.github/workflows/ci.yml

It is already there

**Comment by gurgunday** [comment]
I added node 22

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
